### ISSUE TITLE
Flag to unthrottle Azure Face API

### ISSUE THREAD

**Issue by rswafford** [Webreaper/Damselfly#240]
It would be great if there was a flag to turn off Face API throttling, so on load of a large set of photos I could log into my Azure account, upgrade to the Paid Tier of Face API, and then just let it rip as fast as the server can go - and then ratchet back down to the free tier for ongoing maintenance and smaller loads.

**Comment by Webreaper** [comment]
Question about this - I've not used the paid version of the Face service. When you pay, is there still a trans/sec limit? Or is it entirely unlimited? And if there is still a limit, does it depend on the tier you pay for? 

Reason I ask is I'm wondering if rather than "Don't throttle" I should have config settings for:
- Max transactions per second
- Max transactions per month

which default to the 20 and 30k respectively which are the standard limits for the free tier.

Thoughts?

**Comment by rswafford** [comment]
Yep -- 20 transactions per minute, and 30k per month on the free tier, no max per month on the paid tier, but 10 tx per second.  It's cheap too - $1 per 1000 transactions, up to the first million.

**Comment by Webreaper** [comment]
Yeah, although I did the maths and to run it over my 600,000 photos - given that running face recognition takes around 3 transactions per photo - would still cost me $1800!!

**Comment by Webreaper** [comment]
Okay, this is available now if you pull `webreaper/damselfly:dev`. Will cut a release in a couple of days.

I made the transaction/month limit 30,000,000 - because at 10 txn/sec, that's the most you can do in a month anyway.... :)
