### ISSUE TITLE
Running Damselfly locally

### ISSUE THREAD

**Issue by crypto-rsa** [Webreaper/Damselfly#245]
I have a large photo collection and I am still using Picasa via Wine on Linux. But as you have [discovered](https://github.com/Webreaper/Damselfly/blob/master/docs/Technical.md#why-did-you-build-damsefly) yourself, working with obsolete software is not ideal. So I am keen to try out your application. However, I only store my photos locally (not on a server) and have no experience with Docker. Does Damselfly handle this workflow, too? How can it be run locally?

**Comment by Webreaper** [comment]
Hi, Damselfly can be run anywhere. Docker is easier, because it manages all of the dependencies for you, which means everything will work out of the box with almost zero effort. Can you Install Docker on your desktop?

If not, there are non-Docker binaries with the 2.0.0 release (I don't always build them because most people use Docker) which will run on Windows, Linux or Mac. To run it you just execute it and pass the pictures folder as the only command line arg.

You'll need some dependencies for it to work - exif tool for the keyword tagging and some libs for the AI stuff if you're on Windows or Mac.

**Comment by crypto-rsa** [comment]
Sorry for dumb questions but I think I'll need some more guidance. I've installed Docker and using the command in installation [instructions](https://github.com/Webreaper/Damselfly/blob/master/docs/Installation.md) I was able to run it (with `-v "<path to my images>":/pictures` argument). I was expecting the UI to show up but apparently that's just the server part, right?
Then I discovered the `AppImage` in the release assets, downloaded and ran it. So far so good but when it started, it asked for "URL for Damselfly" and "Local Images Folder". What should be filled in there?

I am still keen to check it out but I think having more detailed instructions to run the program (either remotely or locally) wouldn't hurt.

**Comment by Webreaper** [comment]
The server runs a Webserver. The UI is available by navigating to that in
the browser - so http://localhost:6363 (and that's the same URL for the
settings for the desktop client, but if you're running the server on your
desktop it doesn't make much sense to use the Desktop App).

And yes, more instructions are on my Todo list to add, both for Docker and
for running it without Docker on the desktop.

Let me know if it works!

**Comment by crypto-rsa** [comment]
Hi, sorry for a late reply. Yes, in the end I was able to run it locally. To be honest, I found out it does not fully replace the Picasa experience for me (yet), but keep up the good work! :+1:

**Comment by Webreaper** [comment]
Cool. I'd be interested in features etc that were missing for you, if you can give me a list? I might not implement them, but there's more chance of me doing them if I know!
