### ISSUE TITLE
c:\ is hidden meaning no image show up

### ISSUE THREAD

**Issue by geometrikal** [Webreaper/Damselfly#333]
On my computer `FileUtils.IsHidden` always returns true. Investigation shows that C:\ drive has the Hidden attribute, and thus anything in my Pictures folder doesn't show up. Not sure why C:\ has attribute hidden. 

Suggest stopping the recursive search once the root folder specified in the start up parameters has been reached.

**Comment by Webreaper** [comment]
I don't understand; are you saying that your entire HDD has the hidden flag set? If so, you need to fix that. Even if I made an exception for the root folder (C:\ in this case) Damselfly won't find any files because everything will be in a hidden folder (unless your actual files are all in the root of C:).

You should investigate why IsHidden is true for all your folders.

**Comment by geometrikal** [comment]
@Webreaper 

No, only C:\ gives the hidden flag as set (attribute is 22) all other folders are fine.

**Comment by Webreaper** [comment]
Okay, I see what you mean. So the files aren't being picked up because a parent folder to the Damselfly root is hidden? That does sound wrong. I'll have a look at the code and put in a fix.

Thanks!

**Comment by Webreaper** [comment]
Okay, I've committed a fix - can you give it a try? You can pick it up using the dev tag (so pull `webreaper/damselfly:dev`).

**Comment by geometrikal** [comment]
Yep, works thanks!
