### ISSUE TITLE
question: did you see any benefit from TieredPGO?

### ISSUE THREAD

**Issue by AndyAyersMS** [Webreaper/Damselfly#350]
Notice you seem to have turned this on -- did you see anything good / bad?

Also: we're always on the lookout for good benchmarks or interesting perf issues we can study and learn from.

**Comment by Webreaper** [comment]
Hey Andy, I did some slightly handwavey benchmarks and it appeared that some bits sped up by 5-10%, but it was by no means scientific  (I basically had the app scan a library of photos and do thumbnail generation etc, then did the same thing from scratch but with PGO enabled). I keep meaning to do some slightly more structured benchmarking, but never find the time. 

The main thing is I've seen no ill-effects whatsoever since enabling it.

**Comment by AndyAyersMS** [comment]
Glad to hear at least it's not causing problems -- it drives the runtime/jit in some novel directions.

If you ever do get around to benchmarking, keep me posted.

**Comment by Webreaper** [comment]
I'll try and see if I can pull something together. 

One question - any way to make this a runtime or compiler switch? It would make benchmarking a lot easier. :)

**Comment by Webreaper** [comment]
Did a couple of test runs today, to process just over 1,000 images, and see how timing stats compare with/without PGO enabled. Seems like basically almost no difference at all. Nothing significantly measurable, anyway. 

I suspect that's because the lion's share of the CPU/work overhead is from native code i.e., 

* EMGU face detection, which uses C++ tensorflow libs etc
* Image processing to generate thumbnails, which uses SkiaSharp (which is all wrapped C++)

If I switched out the Skiasharp image processing lib to use ImageSharp (which is all .Net) then perhaps it would see a benefit from PGO). But that wouldn't help much since ImageSharp is currently slower for me to load a JPEG thumb than Skiasharp. 

So at the moment no measurable benefit - but no downside either, so I'll leave it turned on. :)
