### ISSUE TITLE
Config settings aren't always user specific

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/Damselfly#441]
Setting tree view config and themes changes it for all users.

**Comment by dhthwy** [comment]
I looked into this one: 

It seems, from what I can gather, ClientConfigService needs to be scope level instead of singleton in order to make use of AuthStateProvider since the state is per request.

For themes:
By default it was using UserThemeService, which sets the same theme for all users. After taking that out from service reg, it auto switched to ClientThemeService.

After scoping ClientConfigService, it does populate the auth state data. However, the AuthStateChanged handler never gets called.

Fetching the data manually can pull it in:

```
private async void GetUserId()
{
      var authState = await _authProvider.GetAuthenticationStateAsync();
      _userId = authState.GetUserIdFromPrincipal();
}
```
But yeah, having to do that isn't ideal. Looks like it'll have to be done in whichever methods depend on _userId. And Since these calls are async, a logged in user may set configs/themes with _userId not having been set yet by the async call. 

That's why it is changing the theme for all users -- when _userId is unset damselfly defaults to setting it for all users.

**Comment by Webreaper** [comment]
I think it's slightly more complex than this. Remember that with WASM everything is running client side and per-user, so there's almost no difference at all between scoped and singleton in a Blazor Wasm app.

The theme thing I've spent some time debugging and I think it's a race condition, which I introduced when I refactored the code for wasm. The rest of the settings are, I think, just falling back to the "global" (ie non user specific) settings when they haven't been updated for a user.

But maybe you're onto something....

**Comment by dhthwy** [comment]
I am still relatively new to .NET

My understanding is that ClientThemeService is a drop-in replacement for UserThemeService. UserThemeService's code doesn't appear to support per-user theme setting.

During debugging I noticed the behavior for scoped and singleton is different, though. Definitely something strange happening.

**Comment by Webreaper** [comment]
User theme service should reference a UserConfigService, which is what manages the user-specific settings. Altogether possible it's not right though - I haven't spent a huge amount of time on that! :)

**Comment by dhthwy** [comment]
In program.cs: 
```
//builder.Services.AddScoped<AuthenticationStateProvider, ApiAuthenticationStateProvider>();
//builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddSingleton<AuthenticationStateProvider, ApiAuthenticationStateProvider>();
builder.Services.AddSingleton<IAuthService, AuthService>();

```
Changed from scoped to singleton and it works now. ClientConfigService's (as singleton) auth state handler now gets called upon user login/logout (whereas before it wasn't). The singleton vs scoped must've made it use separate auth provider? Not sure. But they're all singleton now in my copy. So theme's or whatever should be able to be set per-user.

Do you agree with this change? Works for me.

**Comment by Webreaper** [comment]
I think that makes sense, and is an excellent spot. I think the scoped would have made sense in Blazor Server, but as you say it should be a singleton for WASM like most of the other objects. 

I've pushed the fix to the develop branch; I can't fully test right now because of internet related problems (I'm about to move house and my broadband got cut off prematurely 🙄) but will check it out once I'm back up and running. 

Thanks again for the fix!

**Comment by dhthwy** [comment]
I am sorry. It may not be enough to fix it. I think I made other changes too. I lost the other edits I made during my experiments.  I'll play with it some more sometime soonish and let you know what else I did, unless you get to it first. :)

**Comment by Webreaper** [comment]
I'll have a play. If you figure it out, please feel free to submit a PR. 

BTW, for some reason you're not showing up as a contributor, despite me merging your last PR. Presuming that's because you have some setting to avoid being listed as a contributor, for privacy or something?

**Comment by Webreaper** [comment]
Finally fixed this yesterday.
