### ISSUE TITLE
Web site from Docker Container completely unresponsive

### ISSUE THREAD

**Issue by andy47** [Webreaper/Damselfly#478]
I installed Damselfly via Docker and pointed it at my large-ish photo library - 28,500 files running to a little over 110Gb - and it's run at 100% capacity for over 2 days.

When I can get a response from the container I've managed to login and check the activity, there are an awful lot of processes that look like this, usually over 50;

    root        3031       7  2 00:59 ?        00:00:00 convert -define jpeg:size=800x800 /pictures/2022/IMG_0312.HEIC -quality 90 -unsharp 0.5x0.5+1.25+0.0

Which looks to me like Damselfly is running some kind of process on each of my photos. 

Is there a way to throttle this so it doesn't use up all of the cpu and memory allotted to my container? If I can limit the amount of work Damselfly is doing on my photos I am hoping that will free up resources to allow me to at least take a look at the web UI.

**Comment by andy47** [comment]
Checking the console it looks like quite a few processes aren't completing. I am seeing a lot of messages like this;

    [ 3533.846671] Out of memory: Killed Process 310937 (convert) total-vm:912312kB, anon-rss:39188kB ...

**Comment by Webreaper** [comment]
I think I know what's going on. I presume most/all of your images are HEIC? If so, the thumbnail conversion for that uses ImageMagick (because the other two native libraries I use for image manipulation don't support HEIC images).

When JPEGs and other images are converted it does throttle to ensure the CPU isn't overwhelmed, but because IM is spawned as a child process that throttling may not be working correctly.

Thanks for logging the issue, I'll look into a fix.

**Comment by andy47** [comment]
I doubled the memory on the VM hosting the container. Same outcome. Thanks for the quick acknowledgement. I would definitely prefer something that takes longer but doesn't thrash my machine to bits.

**Comment by Webreaper** [comment]
Yeah, it's not supposed to thrash!

I think what's happening is that because it's a spawned process, the throttling is only waiting for the launch of the process to start, then triggering the next thumb generation - instead of waiting for the spawned process to complete.

There's another option, which is that Damselfly can generate the thumbs on-demand. I'm not at my computer so can't remember the exact way to turn that on but will ping later. 

I just had a look though, and I think there are better native HEIC libraries since I last looked at this, so I may be able to remove the ImageMagick dependency altogether.

**Comment by Webreaper** [comment]
I added a potential workaround that might work for you. 

If you pull version v4.0.7 and specify the env var `ONDEMAND_THUMBS=true` in your docker command, this will disable background thumbnail generation, and instead use on-demand thumbnails - so the thumbs will be generated as required when you browse images. Note that this will require a machine that can handle that load, otherwise the first time you browse images there might be a short delay as the thumbs are generated (although it is quite quick). 

Let me know if that works for you. In the meantime, I'll look at improving the HEIC thumbnail rendering process so it doesn't require ImageMagick as a spawned process at all.

**Comment by Webreaper** [comment]
Just FYI, having played about with this and seen how much better it works to just create the thumbs on-demand (both from a performance, and a disk-space perspective) I'm changing the way this works for the next major release. So instead of being a cmdline docker option, it'll be a setting in the config page, defaulted to 'On-demand', but with the option for background thumb generation for anyone whose server might not be quick enough to do it on-the-fly. 

I have a couple of bugs to sort out to ensure that thumbs are always refreshed if something changes (e.g., https://github.com/Webreaper/Damselfly/issues/480). It'll also render this issue irrelevant: https://github.com/Webreaper/Damselfly/issues/125
