### ISSUE TITLE
Docker fails on MacOS

### ISSUE THREAD

**Issue by vishvish** [Webreaper/Damselfly#86]
Docker Compose and Build fail:

```
Step 17/34 : RUN dotnet build "Damselfly.Web.csproj" -c Release -o /app/build /p:Version=${DAMSELFLY_VERSION}
 ---> Running in c1df425176a1
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /src/Damselfly.Web/Damselfly.Web.csproj (in 756 ms).
  Restored /src/Damselfly.Core/Damselfly.Core.csproj (in 176 ms).
/usr/share/dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(203,5): error MSB4044: The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion". [/src/Damselfly.Core/Damselfly.Core.csproj]

Build FAILED.

/usr/share/dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(203,5): error MSB4044: The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion". [/src/Damselfly.Core/Damselfly.Core.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.95
The command '/bin/sh -c dotnet build "Damselfly.Web.csproj" -c Release -o /app/build /p:Version=${DAMSELFLY_VERSION}' returned a non-zero code: 1
```

**Comment by Webreaper** [comment]
This is because you need to have the $version ARG set to pass into the command-line. 

I'm reworking the entire build at the moment, with different scripts etc., all using CI/CD in GitHub actions. So you might have to ignore build failures for now.

The previous build compiled the app within the container as part of the docker build and then copied it to the final image. The new flow builds it standalone outside docker and then just copies it into the final image, which means I can use a smaller image as the base.

**Comment by Webreaper** [comment]
Okay, I've tidied this up a bit now. You should be able to do a clean checkout, and then just run `makeall.sh mac` (or just `makeall.sh` - as mac is the default), and it'll build the desktop apps, and run docker for mac. If you want to do the same for linux, just run `makeall.sh linux`. For windows, do `makeall.sh windows`. Let me know if that works better.

**Comment by vishvish** [comment]
Confirmed as working in Docker.
