### ISSUE TITLE
PNG keywords added by ExifTool aren't read correctly

### ISSUE THREAD

**Issue by pppaapp** [Webreaper/Damselfly#91]

**Comment by Webreaper** [comment]
Hi, can you give some more details of what the problem is here? PNG keywords should be updated so I'd like to know what's going wrong. Note that the keywords don't appear instantly on the image, so it might take a couple of minutes after adding for them to show up in the UI (fix pending for that: #59).

Can you confirm:
1. Which version of Damselfly you're using
2. What errors or messages you saw when adding the keyword

Can you also provide logs from the time it happened (these should be in the /config/logs folder for the docker container. If you're able to attach the image you were attempting to add keywords to, that would be helpful to debug too. :)

**Comment by Webreaper** [comment]
Done a bit more investigation on this. The keyword tags are, in fact, being written to the PNG file. However, when Damselfly re-scans the file during indexing to pick up the new keyword metadata, it doesn't read the keywords, because they don't appear to be available for PNG files with the metadata extractor that I'm using.

Tracking here: https://github.com/drewnoakes/metadata-extractor-dotnet/issues/280

**Comment by FewerFlaws** [comment]
While PNG files are capable of holding EXIF data by design, the specific implementation of that is not standardized.  They have EXIF blocks where the data can be written and that's it.  Therefore you can't expect two image metadata programs to interact nicely using PNG files unless they were specifically designed to be compatible with each other.  There simply isn't a protocol.  This is not a bug with Damselfly or ExifTool.

That being said, jpeg and webp do have standardized formats for EXIF data.  If things are failing with those formats then there is a bug present.

**Comment by Webreaper** [comment]
Actually, that's not correct. It's perfectly possible to store ExifData in a PNG, and ExifTool does it just fine. If you use ExifTool to write keywords to a PNG, it can read them back, as can other apps (MacOS Preview, for example, and other image processing apps). The issue in Damselfly is that I use Drew Noakes' Metadata Extractor to read the Exif data from the files, and unfortunately it seems like there's a bug (or a missing feature) which means it's not reading the metadata from the PNG correctly. If you look at the bug report linked above, you'll see Drew and I discuss fixing it - I just haven't had a chance to debug it and submit a PR. :)

**Comment by FewerFlaws** [comment]
Whoops, I briefly glanced at this issue and should've read it more thoroughly.  My apologies =]

**Comment by Webreaper** [comment]
Closed thanks to  drewnoakes/metadata-extractor-dotnet#280 being closed.
